# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20160517_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='_down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='_up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
