# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20160518_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='_lower_bound',
            field=models.FloatField(default=0),
        ),
    ]
